-- Create the table for contact form inquiries
CREATE TABLE public.contact_inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    subject VARCHAR(255),
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add comments to the table and columns
COMMENT ON TABLE public.contact_inquiries IS 'Stores submissions from the website contact form.';
COMMENT ON COLUMN public.contact_inquiries.name IS 'Name of the person making the inquiry.';
COMMENT ON COLUMN public.contact_inquiries.email IS 'Email address of the person.';
COMMENT ON COLUMN public.contact_inquiries.subject IS 'Subject of the message.';
COMMENT ON COLUMN public.contact_inquiries.message IS 'The content of the message/inquiry.';
COMMENT ON COLUMN public.contact_inquiries.created_at IS 'Timestamp when the inquiry was submitted.';

-- Enable Row Level Security (RLS)
ALTER TABLE public.contact_inquiries ENABLE ROW LEVEL SECURITY;

-- Create policy for public insert
-- This allows anyone to submit the form
CREATE POLICY "Allow public insert"
ON public.contact_inquiries
FOR INSERT
WITH CHECK (true);

-- Create policy for admin access
-- This allows users with the 'service_role' or 'authenticated' role to see and manage inquiries
CREATE POLICY "Allow admin full access"
ON public.contact_inquiries
FOR ALL
USING (true);

-- Grant usage on the sequence for the id column to anon and authenticated roles
GRANT USAGE, SELECT ON SEQUENCE contact_inquiries_id_seq TO anon, authenticated; 