-- Create blog_categories table
CREATE TABLE public.blog_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create blog_posts table
CREATE TABLE public.blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    content TEXT NOT NULL,
    category_id BIGINT REFERENCES public.blog_categories(id) ON DELETE SET NULL,
    author_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    status TEXT DEFAULT 'draft' NOT NULL, -- 'draft', 'published', 'scheduled', 'archived'
    publish_date TIMESTAMP WITH TIME ZONE,
    views INT DEFAULT 0 NOT NULL,
    likes INT DEFAULT 0 NOT NULL,
    comments_count INT DEFAULT 0 NOT NULL,
    featured BOOLEAN DEFAULT FALSE NOT NULL,
    thumbnail TEXT,
    excerpt TEXT,
    read_time TEXT,
    tags TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create a function to update `updated_at` column automatically
CREATE OR REPLACE FUNCTION public.update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for blog_posts to update updated_at on change
CREATE TRIGGER update_blog_posts_updated_at
BEFORE UPDATE ON public.blog_posts
FOR EACH ROW
EXECUTE FUNCTION public.update_timestamp();

-- Optional: Add a few default categories
INSERT INTO public.blog_categories (name, slug, description) VALUES
('Travel Tips', 'travel-tips', 'Practical advice and guides for your journeys.'),
('Destinations', 'destinations', 'Explore and discover amazing places to visit.'),
('Culture', 'culture', 'Dive into the rich traditions and customs of various regions.'),
('Wildlife', 'wildlife', 'Fascinating stories and facts about the animal kingdom.'),
('Photography', 'photography', 'Tips and techniques for capturing stunning travel photos.')
ON CONFLICT (slug) DO NOTHING; 